aienginev2: src: Fix compilation error for older GCC version
By default, older GCC versions default to the C90 standard. This causes
compilation errors as modern-day C features like initialization of
control variables in for-statement are not supported.

The compile-time error seen is as follows,
dma/xaie_dma_aie.c:456:2: error: ‘for’ loop initial declarations are only allowed in C99 mode
  for(u8 i = 0U; i < XAIE_TILEDMA_NUM_BD_WORDS; i++) {
  ^

This patch enables the C11 features by explicitly setting the compilation
standard as C11.

Signed-off-by: Nishad Saraf <nishad.saraf@xilinx.com>