aienginev2: src: io_backend: Fix unused variable warning
This patch fixes the below warning.

io_backend/ext/xaie_baremetal.c:50:25: error: unused variable 'BaremetalIO' [-Werror,-Wunused-variable]
static XAie_BaremetalIO BaremetalIO;
                        ^

Signed-off-by: Nishad Saraf <nishad.saraf@xilinx.com>