driver: src: fixed build error for decoupling flow
Resolve build error for decoupling flow. Added missing
header file to CMakeLists.txt.
error logs:
<command-line>: note: this is the location of the previous definition
{color:#de350b}/proj/xhdsswstaff1/krachalw/workspace/aie_decouple/test_bsp/
libsrc/aienginev2/src/device/xaie_device_aieml.c:28:10:
fatal error: xaiemlgbl_params.h: No such file or directory{color}
   28 | #include "xaiemlgbl_params.h"
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [libsrc/aienginev2/src/CMakeFiles/aienginev2.dir/device/xaie_device_aieml.c.obj] Error 1
make[1]: *** Waiting for unfinished jobs....

Signed-off-by: Sandeep Satpute <sandeep.satpute@xilinx.com>

Sankarji Gopalakrishnan